CREATE DATABASE IF NOT EXISTS kopma_030
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'mhs_030'@'localhost' IDENTIFIED BY 'alfazr5634';
GRANT ALL PRIVILEGES ON kopma_030.* TO 'mhs_030'@'localhost';